### ISSUE TITLE
关于densecrf

### ISSUE THREAD

**Issue by brotherNanNan** [wang-ps/O-CNN#1]
dense_learning 项目中似乎没有将crf优化得到的参数写出的代码。请问能给出一套完整的测试示例吗？
我用自己的8类数据进行测试，发现输出的crf.txt中全是0值，不知道代码里对类别有没做限制啊？

**Comment by wang-ps** [comment]
不好意思，由于我的惰性，一直没有写详细的使用说明。过些天我抽空更新一下^_^
类别数目没有限制。你可以检查下，densecrf/examples/dense_learning.cpp的173行load_pointcloud执行之后，结果对不对。然后在239至243行，就会把优化后的参数输出出来。
把这几行输出存到一个文本里，作为dense_inference的输入就可以了。
