### ISSUE TITLE
virtualscanner outputs .points instead of .ply

### ISSUE THREAD

**Issue by mmahdavian** [wang-ps/O-CNN#12]
Hi

I am trying to use the virtualscanner to get point cloud in .ply format. But it currently outputs .points format file. Have you had any versions which used to output .ply file?

Thank You

**Comment by wang-ps** [comment]
You can use the `PyMesh` package to load the `ply` file and save it to `obj` file:
https://pymesh.readthedocs.io/en/latest/basic.html
