### ISSUE TITLE
How to convert laptop_0104.off by the suggested number of views for scanning?

### ISSUE THREAD

**Issue by giechow** [wang-ps/O-CNN#2]
I am converting ModelNet40 into ".points" files.
While the rest files are converted successfully, I cannot convert "laptop_0104.off" by the suggested 14 views.
I can scan it only when I reduce the number of views to 6.
How can I convert "laptop_0104.off" by 14 views of scanning?

**Comment by wang-ps** [comment]
It is a bug of CGAL. 
I scale this model, then it is fine. Download it ( [laptop_0104.zip](https://github.com/wang-ps/O-CNN/files/1633797/laptop_0104.zip) ), and have a try.

**Comment by giechow** [comment]
Thank you!
