### ISSUE TITLE
Can I output 3d mesh file(obj file, etc..) with segementation

### ISSUE THREAD

**Issue by Aki1987** [wang-ps/O-CNN#3]
Thank you for your work.
Can I ask you a question.
In Fig9 of your paper"O-CNN: Octree-based Convolutional Neural Networks for 3D Shape Analysis", how you generate the picture?

**Comment by wang-ps** [comment]
I uploaded a tool `octree2ply` to this [repository](https://github.com/Microsoft/O-CNN) which can be used to convert the octree to the ply file, as well as a txt file contains the segmentation label.
Then the point cloud and label can be rendered with OpenGL or some software that can display point cloud.

**Comment by Aki1987** [comment]
Thank you for your reply. I will try it.
